// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWp2K800GDXvUyoajHy0ClX7lw6b_RRSI',
    appId: '1:292149580562:web:19bcd103f8ab38b08a59cb',
    messagingSenderId: '292149580562',
    projectId: 'chat-app-cbd9a',
    authDomain: 'chat-app-cbd9a.firebaseapp.com',
    storageBucket: 'chat-app-cbd9a.appspot.com',
    measurementId: 'G-W4KB4L3WN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalJzqTU_owL9KvnSYR-JJ5K0pYFqrUlQ',
    appId: '1:292149580562:android:68c1ffed7906e6858a59cb',
    messagingSenderId: '292149580562',
    projectId: 'chat-app-cbd9a',
    storageBucket: 'chat-app-cbd9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZOMnLmUqoOjUbygQuXEhtou0ZeEEmcA',
    appId: '1:292149580562:ios:c1ed11ad4eefa2ba8a59cb',
    messagingSenderId: '292149580562',
    projectId: 'chat-app-cbd9a',
    storageBucket: 'chat-app-cbd9a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsZOMnLmUqoOjUbygQuXEhtou0ZeEEmcA',
    appId: '1:292149580562:ios:3dee808156b817c08a59cb',
    messagingSenderId: '292149580562',
    projectId: 'chat-app-cbd9a',
    storageBucket: 'chat-app-cbd9a.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
